### ISSUE TITLE
Create README file for CircleCI-Public org

### ISSUE THREAD

**Issue by jerdog** [CircleCI-Public/.github#1]
In conversation with @tjmcs about creating a README for our Public repo... Some things that we could put in here could be links to Docs, DevHub, Videos, orbs, etc.

**Comment by jerdog** [comment]
adding @felicianotech

**Comment by kiajfaty** [comment]
> In conversation with @tjmcs about creating a README for our Public repo... Some things that we could put in here could be links to Docs, DevHub, Videos, orbs, etc.

**Comment by tjmcs** [comment]
I also like to add links to "process-related" docs that you might create to my `README.md` files (like a `CONTRIBUTING.md` file explaining the "rules of the road" to a new developer who wants to contribute); I'm not sure what that complete list would be, but I'm sure there are a few of those we could link to...

**Comment by jerdog** [comment]
Yeah my thought was to add links to DevHub, Docs, Discuss, Blog, etc., and then describe the contribution process with a link to what we use, and other items of interest

**Comment by tjmcs** [comment]
Closing now that #33 has been merged
